Feature user prefs
devs-coffee/backend-collab-chat-project pull request #68
Opened 2023-08-07 14:22 UTC by WhitedogWarren

2023-08-07 17:06 UTC, julienb86 requested changes

2023-08-07 17:06 UTC, julienb86 commented on src/dtos/users/user.dto.ts
> +    prefs?: PrefsDto
Pareil pourquoi avoir cette propriété qui peut être optionnelle?

2023-08-07 17:06 UTC, julienb86 commented on src/users/users.controller.ts
> +      if(serviceResponse!) {
pourquoi un ! sur un objet qui sera possiblement null?
Aussi il serait mieux de retourner l'objet plutôt qu un booléen dans la réponse du controller

2023-08-08 05:46 UTC, WhitedogWarren commented on prisma/schema.prisma
> +  colorScheme   String
Oui, je me suis posé la question. Ok, on part là dessus

2023-08-08 05:48 UTC, WhitedogWarren commented on src/core/automapping.ts
> +            createMap(mapper, UserEntity, UserDto, forMember(user => user.prefs, mapFrom(u => u.prefs)));
Je vais regarder ça, mais je crois qu'on avait eu le souci avec les channels à intégrer dans un server.
De plus, au départ je m'étais un peu planté en mettant pref au singulier dans le prisma.schema. ^^

2023-08-08 05:50 UTC, WhitedogWarren commented on src/dtos/users/prefs.dto.ts
> +    userId?: string;
Alors ça, c'est pour que le service puisse rechercher les prefs. Mais c'est inutile de l'envoyer dans le body ( on recherche la pref selon l'userId récupéré depuis le token ) et de le renvoyer dans la réponse.
À voir, je vais essayer de le supprimer.

2023-08-08 05:51 UTC, WhitedogWarren commented on src/dtos/users/user.dto.ts
> +    prefs?: PrefsDto
Quand on récupère un user autre que soi-même, on ne récupère pas ses prefs.
En revanche, quand on récupère ses propres infos lors d'un login ou d'un getMe, on les récupère.

2023-08-08 05:52 UTC, WhitedogWarren commented on src/users/users.controller.ts
> +      if(serviceResponse!) {
Oh, ça c'est probablement quand j'ai galéré à mettre en place le routeur et le contrôleur.
Je vois pour le virer.

2023-08-08 05:53 UTC, WhitedogWarren commented on src/users/users.service.ts
> +import { PrefsDto } from 'src/dtos/users/prefs.dto';
Bien vu. Bizarre, en local il ne m'a pas fait de misère, contrairement à d'habitude ^^

2023-08-08 15:52 UTC, WhitedogWarren commented on src/dtos/users/prefs.dto.ts
> +    userId?: string;
Done

2023-08-08 16:01 UTC, WhitedogWarren commented on src/users/users.controller.ts
> +      if(serviceResponse!) {
Done

2023-08-08 16:02 UTC, WhitedogWarren commented on src/users/users.service.ts
> +import { PrefsDto } from 'src/dtos/users/prefs.dto';
Done

2023-08-11 10:53 UTC, julienb86 approved these changes

2023-08-11 10:53 UTC, merged